language: python

python:
  - "2.7"

sudo: required

os:
  - linux

script:
  - /bin/bash ./run_test.sh
  - flake8 `find . -name "*.py"`

notifications:
  email:
    on_success: change
    on_failure: always
